[package]
name = "libwallet"
version = "0.1.0"
authors = ["Daniel Olano <me@olanod.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.51"
sp-core = { version = "3.0.0", default-features = false, features = ["full_crypto"] }
thiserror = { version = "1.0.30", optional = true }
serde = { version = "1.0", features = ["derive", "rc"], optional = true}
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
regex = { version = "1.5.4", optional = true}
keyring = "1.1.2"

[dev-dependencies]
clap = "2.33.3"
async-std = { version = "1.10.0", features = ["attributes"] }

[features]
default = ["std", "simple", "substrate"]
substrate = []
simple = []
std = [
	"thiserror",
	"sp-core/std",
	"serde",
	"regex",
]
